name: Testing data
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    env:
      WHYLABS_API_KEY: ${{ secrets.WHYLABS_API_KEY }}
      WHYLABS_DEFAULT_ORG_ID: ${{ secrets.WHYLABS_DEFAULT_ORG_ID }}}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Creating and activating virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip install -r requirements.txt
      - name: Testing training
        run: |
          pytest tests/test_model.py
